<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

if (!(isset($_POST['isim']) && isset($_POST['email']) && isset($_POST['mesaj']))) {

    echo json_encode(array(
        "result" => "Lütfen gerekli tüm alanları doldurunuz.",
        "code" => 1
    ));

    exit();
}

if (mb_strlen($_POST['isim']) == 0 || mb_strlen($_POST['email']) == 0 || mb_strlen($_POST['mesaj']) == 0) {
    echo json_encode(array(
        "result" => "Lütfen gerekli tüm alanları doldurunuz.",
        "code" => 2
    ));

    exit();
}

if (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)) {
    echo json_encode(array(
        "result" => "Geçersiz bir e-posta adresi girdiniz.",
        "code" => 3
    ));
    exit();
}

// isim, email, telefon, mesaj
$post_fields = "------WebKitFormBoundaryTbgYCMCPLPbZ0c0U\r\nContent-Disposition: form-data; name=\"_e24a3f20f821168407b12b5e0b33dfcc\"\r\n\r\n%s\r\n------WebKitFormBoundaryTbgYCMCPLPbZ0c0U\r\nContent-Disposition: form-data; name=\"_aec7b7ca6b6176f262e1d5847a9f2f2f\"\r\n\r\n%s\r\n------WebKitFormBoundaryTbgYCMCPLPbZ0c0U\r\nContent-Disposition: form-data; name=\"_bbd1a1637937fb95902c9985642b4691\"\r\n\r\n%s\r\n------WebKitFormBoundaryTbgYCMCPLPbZ0c0U\r\nContent-Disposition: form-data; name=\"_57670dc2e0c6e9468557e2c2d79c3a1e\"\r\n\r\n%s\r\n------WebKitFormBoundaryTbgYCMCPLPbZ0c0U\r\nContent-Disposition: form-data; name=\"cid_207\"\r\n\r\n\r\n------WebKitFormBoundaryTbgYCMCPLPbZ0c0U--";
$post_fields = sprintf($post_fields, $_POST['isim'], $_POST['email'], $_POST['telefon'], $_POST['mesaj']);

curl_setopt($ch, CURLOPT_URL, "http://www.coverevi.com/index.php/iletisim/iletisim");
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_fields);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$headers = array();
$headers[] = "Cookie: _ga=GA1.2.438347141.1487418167; 0a507ef745a73c26edbda6042ed90523=3902741f4488a465e81bbf69dd2920fd";
$headers[] = "Origin: http://www.coverevi.com";
$headers[] = "Accept-Encoding: gzip, deflate";
$headers[] = "Accept-Language: en-US,en;q=0.8,tr;q=0.6";
$headers[] = "Upgrade-Insecure-Requests: 1";
$headers[] = "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36";
$headers[] = "Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTbgYCMCPLPbZ0c0U";
$headers[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8";
$headers[] = "Cache-Control: max-age=0";
$headers[] = "Referer: http://www.coverevi.com/index.php/iletisim/iletisim";
$headers[] = "Connection: keep-alive";
$headers[] = "Dnt: 1";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

curl_close ($ch);

echo json_encode(array(
    "result" => "Teşekkürler, mesajınız bize iletilmiştir. En kısa sürede geri dönüş yapılacaktır.",
    "code" => 1
));